Vas a crear una estrategia:
nombre: ESTRATEGIA INTEGRAL PARA LA PREVENCIÓN DE LAS VIOLENCIA CONTRA LOS ANIMALES
Objetivo: IMPLEMENTAR UNA ESTRATEGIA PEDAGÓGICA Y COMUNITARIA, BASADA EN GUÍAS METODOLÓGICAS CONSTRUIDAS DE FORMA PARTICIPATIVA DURANTE EL PROCESO DE FORMULACIÓN DE LA POLÍTICA PÚBLICA DE PROTECCIÓN Y BIENESTAR ANIMAL, QUE PERMITA PREVENIR Y ATENDER DE MANERA INTEGRAL LOS ESCENARIOS DE RIESGO ASOCIADOS A LAS VIOLENCIAS CONTRA LOS ANIMALES EN EL DEPARTAMENTO DEL VALLE DEL CAUCA.

Meta del producto asociado: OPERATIVIZAR 1 ESTRATEGIA QUE GARANTICE EL CUMPLIMIENTO DE LA POLÍTICA DE PROTECCIÓN Y BIENESTAR ANIMAL EN TÉRMINOS DE PREVENCIÓN DEL RIESGO DE VIOLENCIA Y GOBERNANZA INTERINSTITUCIONAL EN EL PERIODO DE GOBIERNO

Programacion de la meta: Año 1, meta: 100

Después vas a crear varios componentes asociados a esta estrategia.

Componentes:
1.
Estrategia id: la que creamos
Nombre: ANIMALES COMO EMBAJADORES DE PAZ	
Objetivos: CREAR ESCENARIOS DONDE LOS ANIMALES SON CLAVES PARA LA RECUPERAICON, REHABILITACION Y APOYO EMOCIONAL PARA LOS DIFERENTES TIPOS DE POBLACIONES	
Actividades mga:
DESARROLLAR LA METODOLOGÍA PARA LA PREVENCIÓN DE LOS RIESGOS DE VIOLENCIAS CONTRA LOS ANIMALES	
Inicadores:
    Nombre: LOL
    Tipo: Number
    Obligatorio: si
    Metas anuales: año: 2026, meta: 2

(Vas a crear todos los componentes con esos indicadores)

2.
Nombre:  ASISTENCIAS TECNICAS A ACTORES INSTITUCIONALES DE LA ADMINISTRACION PUBLICA 	
Objetivos: BRINDAR ASISTENCIAS TÉCNICAS ESPECIALIZADAS A LAS ENTIDADES TERRITORIALES DEL DEPARTAMENTO, ORGANIZADAS POR MICROREGIONES, CON EL FIN DE FORTALECER SUS CAPACIDADES INSTITUCIONALES, TÉCNICAS Y OPERATIVAS PARA LA IMPLEMENTACIÓN, SEGUIMIENTO Y CUMPLIMIENTO DE LA POLÍTICA PÚBLICA DE PROTECCIÓN Y BIENESTAR ANIMAL.	
Actividades mga:
OPERATIVIZAR EL COMITÉ INTERDISCIPLINARIO, CON SABERES FINANCIEROS, JURÍDICOS, SOCIALES Y MEDICO VETERINARIOS, PARA LA ASESORÍA Y ACOMPAÑAMIENTO A LOS GRUPOS DE INTERÉS COMPETENTES EN LA POLÍTICA PÚBLICA DE PROTECCIÓN Y BIENESTAR ANIMAL	

3.
Nombre: RUTA DE ATENCION 
Objetivos: FORTALECER LA RUTA DE ATENCIÓN PYBA MEDIANTE LA ARTICULACIÓN DE LOS CANALES DE DENUNCIA, EL FORTALECIMIENTO DEL PROCESO ADMINISTRATIVO Y JURÍDICO, Y LA GARANTÍA DE LA RESPUESTA OPORTUNA, ATENCIÓN Y SOLUCIÓN EFECTIVA DE LOS CASOS DE PROTECCIÓN Y BIENESTAR ANIMAL.	
Actividades mga:
EJECUTAR ACCIONES DE APOYO TÉCNICO Y OPERATIVO A LOS SERVICIOS DE INSPECCIÓN, VIGILANCIA Y CONTROL, MEDIANTE LA IMPLEMENTACIÓN DE LA RUTA DE PROTECCIÓN Y ATENCIÓN ANIMAL

4.
Nombre: TURISMO MULTIESPECIE
Objetivos: CREAR UNA ESTARTEGIA DE TURIMO MULTIESPECIA DONDE SE GARANTICE EL RESPETO POR LOS ANIMALES A  TRAVEZ DE UNA METODOLOGIA CLARA Y CON IMPACTO 	
Actividades mga:
DESARROLLAR LA METODOLOGÍA PARA LA PREVENCIÓN DE LOS RIESGOS DE VIOLENCIAS CONTRA LOS ANIMALES

5. 
Nombre: ENFOQUE DIFERENCIAL
Objetivos: IMPLEMENTAR PROGRAMA DE GUARDIANTES DE HUELLA EN ARTICULACION CON LA SECRETARIA DE MUJER.

IMPLEMENTAR PROGRAMA DE LOS ANIMALES COMO VICTIMAS DEL CONFLICTO ARMADO.
Actividades mga:
DESARROLLAR LA METODOLOGÍA PARA LA PREVENCIÓN DE LOS RIESGOS DE VIOLENCIAS CONTRA LOS ANIMALES

DESARROLLAR LA METODOLOGÍA PARA LA PREVENCIÓN DE LOS RIESGOS DE VIOLENCIAS CONTRA LOS ANIMALES


6. 
Nombre: OBSERVATORIO/PLATAFORMA
Objetivos: IMPLEMENTAR UNA PLATAFORMA VIRTUAL QUE PERMITA EL REGISTRO, GESTIÓN, SEGUIMIENTO Y VISUALIZACIÓN DE LA INFORMACIÓN RELACIONADA CON LA PROTECCIÓN Y BIENESTAR ANIMAL, COMO SOPORTE PARA LA TOMA DE DECISIONES, EL MONITOREO DE INDICADORES Y LA ARTICULACIÓN INSTITUCIONAL.

Actividades mga:
IMPLEMENTAR EL OBSERVATORIO DEPARTAMENTAL DE POLÍTICA PÚBLICA DE PROTECCIÓN Y BIENESTAR ANIMAL

Otra estrategia:
nombre: Centros de bienestar animal por microregiones
Objetivo: 
FORTALECER LA OPERACIÓN Y CAPACIDAD TÉCNICA DE LOS CENTROS DE BIENESTAR ANIMAL DEL DEPARTAMENTO DEL VALLE DEL CAUCA, MEDIANTE EL ACOMPAÑAMIENTO Y ASESORÍA TÉCNICA A LOS PROCESOS QUE DESARROLLAN, ASÍ COMO LA DOTACIÓN DE CENTROS DE BIENESTAR ANIMAL REGIONALES, CON EL FIN DE GARANTIZAR LA ATENCIÓN INTEGRAL, OPORTUNA Y ADECUADA DE LOS ANIMALES EN SITUACIÓN DE VULNERABILIDAD, EN EL MARCO DE LA POLÍTICA PÚBLICA DE PROTECCIÓN Y BIENESTAR ANIMAL.
Meta del producto asociado: DOTAR TRES CENTROS DE BIENESTAR ANIMAL REGIONAL PARA EL DEPARTAMENTO DEL VALLE DEL CAUCA EN EL PERIODO DE GOBIERNO

Programacion de la meta: Año 1, meta: 100

Después vas a crear varios componentes asociados a esta estrategia.

Componentes:
1.
Nombre: CENTROS DE BIENESTAR ANIMAL
Objetivos: FORTALECER LOS PROCESOS TÉCNICOS, OPERATIVOS Y ADMINISTRATIVOS DE LOS CENTROS DE BIENESTAR ANIMAL DEL DEPARTAMENTO DEL VALLE DEL CAUCA, MEDIANTE LA PRESTACIÓN DE ASISTENCIA TÉCNICA ESPECIALIZADA QUE PERMITA MEJORAR LA CALIDAD DE LA ATENCIÓN, EL CUMPLIMIENTO DE LOS PROTOCOLOS Y LA IMPLEMENTACIÓN DE LA POLÍTICA PÚBLICA DE PROTECCIÓN Y BIENESTAR ANIMAL.

DOTAR CENTROS DE BIENESTAR ANIMAL REGIONALES DEL DEPARTAMENTO DEL VALLE DEL CAUCA CON EL EQUIPAMIENTO, INSUMOS Y ELEMENTOS NECESARIOS PARA SU ADECUADA OPERACIÓN, CON EL FIN DE GARANTIZAR UNA ATENCIÓN INTEGRAL, OPORTUNA Y DIGNA A LOS ANIMALES EN SITUACIÓN DE VULNERABILIDAD.
Actividades mga:
Asesorar técnica y administrativamente los procesos desarrollados por los centros de bienestar animal regional

Dotar los centros de bienestar animal regional con insumos definidos concertadamente

Otra estrategia:
nombre: ATENCION PRIMARIA EN SALUD
Objetivo: 
IMPLEMENTAR UNA ESTRATEGIA INTEGRAL DE ATENCIÓN PRIMARIA EN SALUD PARA LOS ANIMALES DEL DEPARTAMENTO DEL VALLE DEL CAUCA, QUE PERMITA BRINDAR SERVICIOS PREVENTIVOS Y ASISTENCIALES BÁSICOS, ASÍ COMO GENERAR DIAGNÓSTICOS E INFORMACIÓN EPIDEMIOLÓGICA QUE SIRVA COMO BASE PARA PREVENIR ENFERMEDADES, MUERTES Y AFECTACIONES QUE COMPROMETAN EL BIENESTAR ANIMAL
Meta del producto asociado: ATENDER 10.000 ANIMALES MEDIANTE LA PREVENCIÓN, DIAGNÓSTICO Y CURA DE SITUACIONES DERIVADAS POR ABANDONO, PERDIDA, DESATENCIÓN, TENENCIA IRRESPONSABLE O VULNERABILIDAD EN EL PERIODO DE GOBIERNO

Programacion de la meta: Año 1, meta: 100

Después vas a crear varios componentes asociados a esta estrategia.

Componentes:
1.
Nombre: ATENCION EN SALUD ANIMAL COMPAÑEROA TRAVES DE LA UNIDAD MOVIL
Objetivos: REALIZAR JORNADAS DE ATENCION INTEGRAL EN SALUD Y BIENESTAR PARA LOS ANIMALES,  A TRAVES DE LA UNIDAD MOVIL EN LOS DIFERENTES MUNICIPIOS DEL DEPARTAMENTO DEL VALLE 

Actividades mga:
REALIZAR JORNADAS DE ATENCIÓN INTEGRAL PARA LOS ANIMALES UBICADOS EN LOS ESTRATOS SOCIOECONÓMICOS MÁS VULNERABLES O EN SITUACIÓN DE ABANDONO.

2.
Nombre: ATENCION EN SALUD ANINMAL COMPAÑERO EQUIPO DE CAMPO
Objetivos: REALIZAR JORNADAS DE ATENCION INTEGRAL EN SALUD Y BIENESTAR PARA LOS ANIMALES, A TRAVES DEL EQUIPO  DE CAMPO EN LOS DIFERNTES ALBERGUES Y ESPACIOS DELEGADOS. 

Actividades mga:
REALIZAR JORNADAS DE ATENCIÓN INTEGRAL PARA LOS ANIMALES UBICADOS EN LOS ESTRATOS SOCIOECONÓMICOS MÁS VULNERABLES O EN SITUACIÓN DE ABANDONO.

3.
Nombre: FORTALECIMIENTO Y ATENCION INTEGRAL PARA ANIMALES DE GRANJA Y DE PRODUCCION 
Objetivos: 
FORTALECER LOS PROCESOS RELACIONADOS CON EL MANEJO, CUIDADO Y BIENESTAR DE LOS ANIMALES DE GRANJA Y PRODUCCIÓN, MEDIANTE LA ARTICULACIÓN INTERINSTITUCIONAL CON LAS ENTIDADES COMPETENTES, PROMOVIENDO LA IMPLEMENTACIÓN DE ENFOQUES DE RESPETO, BUENAS PRÁCTICAS Y CORRESPONSABILIDAD EN EL MARCO DE LA POLÍTICA PÚBLICA DE PROTECCIÓN Y BIENESTAR ANIMAL. 
Actividades mga:
ELABORAR DIAGNOSTICOS POBLACIONALES QUE CARACTERICEN E IDENTIFIQUEN LAS ZONAS DONDE SE DEMANDA ATENCIÓN INTEGRAL PARA ANIMALES EN SITUACIÓN DE ABANDONO, PERDIDA, DESATENCIÓN, TENENCIA IRRESPONSABLE O VULNERABILIDAD

4.
Nombre: EQUIPO URIA (VETERINARIOS - PSICOLOGO - ABOGADO) 
Objetivos: 
IMPLEMENTAR LAS ACCIONES PARA BRINDAR ATENCION A LOS ANIMALES DE FORMA INMEDIATA
Actividades mga:
REALIZAR JORNADAS DE ATENCIÓN INTEGRAL PARA LOS ANIMALES UBICADOS EN LOS ESTRATOS SOCIOECONÓMICOS MÁS VULNERABLES O EN SITUACIÓN DE ABANDONO.

Otra estrategia:
nombre: ESTRATEGIA DE DESARROLLO ECONOMICO
Objetivo: 
FORTALECER EL DESARROLLO ECONÓMICO DE LOS ACTORES DEL ECOSISTEMA DE PROTECCIÓN Y BIENESTAR ANIMAL EN EL DEPARTAMENTO DEL VALLE DEL CAUCA, A TRAVÉS DE UNA ESTRATEGIA TRANSVERSAL DE COFINANCIACIÓN, ASISTENCIA TÉCNICA Y PROMOCIÓN DE INICIATIVAS PRODUCTIVAS SOSTENIBLES, QUE CONTRIBUYAN A LA AUTOSUFICIENCIA, SOSTENIBILIDAD Y DIGNIFICACIÓN DE SU LABOR EN EL TERRITORIO.
Meta del producto asociado: COFINANCIAR A 40 ACTORES PERTENECIENTES A JUNTAS DE PROTECCIÓN ANIMAL, REDES DE RESCATISTAS, ANIMALISTAS, ALBERGUES, PROTECCIONISTAS, FUNDACIONES Y OTROS A FINES A LA PROTECCIÓN Y BIENESTAR ANIMAL EN EL PERIODO DE GOBIERNO
Programacion de la meta: Año 1, meta: 100

Después vas a crear varios componentes asociados a esta estrategia.

Componentes:
1.
Nombre: CLÚSTER EMPRESARIAL
Objetivos: CONSOLIDAR UNA RED EMPRESARIAL DE EMPRENDEDORES DEL SECTOR DE PROTECCIÓN Y BIENESTAR ANIMAL QUE FORTALEZCA EL ECOSISTEMA ECONÓMICO, LA ARTICULACIÓN Y LA SOSTENIBILIDAD DEL SECTOR PYBA.
Actividades mga:
ACOMPAÑAR TÉCNICAMENTE LAS ACCIONES DESARROLLADAS POR ACTORES QUE PROTEGEN ANIMALES EN SITUACIÓN DE ABANDONO, VULNERABILIDAD O TENENCIA IRRESPONSABLE
2.
Nombre: AUTOSOSTENIBILIDAD DE REFUGIOS 
Objetivos: IMPULSAR LA AUTOSOSTENIBILIDAD ECONÓMICA DE LOS REFUGIOS DE PROTECCIÓN ANIMAL MEDIANTE LA IMPLEMENTACIÓN DE MODELOS DE INGRESOS QUE DISMINUYAN LA DEPENDENCIA DE LAS DONACIONES.
Actividades mga:
SUMINISTRAR INSUMOS A LOS ACTORES VOLUNTARIOS QUE PROTEGEN ANIMALES EN SITUACIÓN DE ABANDONO, VULNERABILIDAD O TENENCIA IRRESPONSABLE
3.
Nombre: EMPRENDIMIENTOS CONSCIENTES VALLEINN
Objetivos: COFINANCIAR EMPRENDIMIENTOS CONSCIENTES A TRAVES DE LOS PROGRAMAS DE LA SECRETARIA DE DESARROLLO ECONOMICO
Actividades mga:
SUMINISTRAR INSUMOS A LOS ACTORES VOLUNTARIOS QUE PROTEGEN ANIMALES EN SITUACIÓN DE ABANDONO, VULNERABILIDAD O TENENCIA IRRESPONSABLE
4.
Nombre: ALIANZAS ESTRATEGICAS
Objetivos: GENERAR Y CONSOLIDAR ALIANZAS ESTRATEGICAS QUE FORTALEZCAN LAS REDES DE ACTORES CREADAS
Actividades mga:
ACOMPAÑAR TÉCNICAMENTE LAS ACCIONES DESARROLLADAS POR ACTORES QUE PROTEGEN ANIMALES EN SITUACIÓN DE ABANDONO, VULNERABILIDAD O TENENCIA IRRESPONSABLE

Otra estrategia:
nombre: estrategia de articulacion comunitaria 
Objetivo: 
CREAR Y FORTALECER REDES DE ACTORES DEL ECOSISTEMA DE PROTECCIÓN Y BIENESTAR ANIMAL CON PARTICIPACIÓN COMUNITARIA, PROMOVIENDO LA ARTICULACIÓN TERRITORIAL, EL TRABAJO COLABORATIVO Y LA MOVILIZACIÓN SOCIAL EN TORNO A LA DEFENSA DE LOS ANIMALES COMO SERES SINTIENTES.
Meta del producto asociado: CREAR Y SOSTENER 3 REDES DE ACTORES 
Programacion de la meta: Año 1, meta: 100

Después vas a crear varios componentes asociados a esta estrategia.

Componentes:
1.
Nombre: DONATON SALVANDO HUELLAS
Objetivos: SUMINISTRAR ALIMENTO A LOS REFUGIOS ALBERGUES O FUNDACIONES QUE TENGAN ANIMALES  
Actividades mga:
SUMINISTRAR INSUMOS A LOS ACTORES VOLUNTARIOS QUE PROTEGEN ANIMALES EN SITUACIÓN DE ABANDONO, VULNERABILIDAD O TENENCIA IRRESPONSABLE

2.
Nombre: RED ANIMALIA 
Objetivos: FORTALECER LA RED ANIMALIA MEDIANTE LA CAPACITACIÓN Y EL ACOMPAÑAMIENTO TÉCNICO A LOS ACTORES QUE LA CONFORMAN, ASÍ COMO LA CONSOLIDACIÓN DE REDES ORGANIZADAS POR CATEGORÍAS, CON EL FIN DE MEJORAR LA ARTICULACIÓN, EL INTERCAMBIO DE CAPACIDADES Y LA EFECTIVIDAD DE LAS ACCIONES DESARROLLADAS EN MATERIA DE PROTECCIÓN Y BIENESTAR ANIMAL.  
Actividades mga:
ACOMPAÑAR TÉCNICAMENTE LAS ACCIONES DESARROLLADAS POR ACTORES QUE PROTEGEN ANIMALES EN SITUACIÓN DE ABANDONO, VULNERABILIDAD O TENENCIA IRRESPONSABLE

3.
Nombre: ACOMPÁÑAMIENTO PSICOSOCIAL
Objetivos: 
FORTALECER LA SALUD MENTAL DE CUIDADORES Y RESCATISTAS A TRAVÉS DE PROCESOS DE ACOMPAÑAMIENTO PSICOSOCIAL QUE MITIGUEN EL DESGASTE EMOCIONAL ASOCIADO A LA PROTECCIÓN Y BIENESTAR ANIMAL.
Actividades mga:
ACOMPAÑAR TÉCNICAMENTE LAS ACCIONES DESARROLLADAS POR ACTORES QUE PROTEGEN ANIMALES EN SITUACIÓN DE ABANDONO, VULNERABILIDAD O TENENCIA IRRESPONSABLE

4.
Nombre: REALIZAR LA INSPECCION DE ALBERGUES
Objetivos: 
GENERAR UN DOCUMENTO TECNICO DONDE SE EVIDENCIEN CUALES SON LAS NECESIDADES Y REQUERMIENTOS OPERATIVOS QUE TIENEN LOS ALBERGUES EN EL DEPARTAMENTO DEL VALLE DEL CAUCA 
Actividades mga:
ELABORAR DIAGNOSTICOS POBLACIONALES QUE CARACTERICEN E IDENTIFIQUEN LAS ZONAS DONDE SE DEMANDA ATENCIÓN INTEGRAL PARA ANIMALES EN SITUACIÓN DE ABANDONO, PERDIDA, DESATENCIÓN, TENENCIA IRRESPONSABLE O VULNERABILIDAD

5.
Nombre: PROGRAMA DE ADOPCIONES
Objetivos: 
PROMOVER LA ADOPCIÓN RESPONSABLE DE LOS ANIMALES CON EL FIN DE DISMINUIR LOS ANIMALES EN SITUACIÓN DE ABANDONO
Actividades mga:
ACOMPAÑAR TÉCNICAMENTE LAS ACCIONES DESARROLLADAS POR ACTORES QUE PROTEGEN ANIMALES EN SITUACIÓN DE ABANDONO, VULNERABILIDAD O TENENCIA IRRESPONSABLE

6.
Nombre: JUNTAS DEFENSORAS DE ANIMALES 
Objetivos: 
PONER EN MARCHA LAS JUNTAS DEFENSORAS DE ANIMALES A TRAVÉS DE PROCESOS DE CAPACITACIÓN Y ACOMPAÑAMIENTO TÉCNICO QUE FORTALEZCAN SU ROL EN LA PROTECCIÓN Y BIENESTAR ANIMAL.
Actividades mga:
ACOMPAÑAR TÉCNICAMENTE LAS ACCIONES DESARROLLADAS POR ACTORES QUE PROTEGEN ANIMALES EN SITUACIÓN DE ABANDONO, VULNERABILIDAD O TENENCIA IRRESPONSABLE

Otra estrategia:
nombre: ESTRATEGIA EDUACTIVA PYBA
Objetivo: 
DISEÑAR E IMPLEMENTAR ESTRATEGIAS PEDAGÓGICAS, BASADAS EN GUÍAS OPERATIVAS, QUE PERMITAN CAPACITAR Y FORMAR A DIVERSOS GRUPOS POBLACIONALES EN TEMAS DE PROTECCIÓN Y BIENESTAR ANIMAL, FOMENTANDO UNA CULTURA DE RESPETO HACIA LOS ANIMALES COMO SERES SINTIENTES.
Meta del producto asociado: CAPACITAR 10.000 PERSONAS EN PROCESOS DE BIENESTAR ANIIMAL, DESDE LA VISIÓN DE RESPETO Y RECONOCIMIENTO COMO SERES SINTIENTES, DURANTE EL PERIODO DE GOBIERNO
Programacion de la meta: Año 1, meta: 100

Después vas a crear varios componentes asociados a esta estrategia.

Componentes:
1.
Nombre:PROMOTORES PYBA
Objetivos: DESARROLLAR PROCESOS DE CAPACITACIÓN DIRIGIDOS A LAS DIFERENTES POBLACIONES DEL DEPARTAMENTO DEL VALLE DEL CAUCA, MEDIANTE LA IMPLEMENTACIÓN DEL PENSUM EDUCATIVO PYBA, CON EL FIN DE PROMOVER UNA CULTURA DE RESPETO, CUIDADO Y CORRESPONSABILIDAD HACIA LOS ANIMALES.
Actividades mga:
CAPACITAR A LOS GRUPOS DE INTERÉS RELACIONADOS CON LA PROTECCION Y EL BIENESTAR ANIMAL EN PROCESOS DE INCLUSIÓN Y RESPETO HACIA LOS ANIMALES

2.
Nombre:IMPLEMENTAR EL PROGRAMA ESCUADRON BENJI PRIMERA INFANCIA
Objetivos: IMPLEMENTAR EL PROGRAMA ESCUADRON BENJI PRIMERA INFANCIA
Actividades mga:
CAPACITAR A LOS GRUPOS DE INTERÉS RELACIONADOS CON LA PROTECCION Y EL BIENESTAR ANIMAL EN PROCESOS DE INCLUSIÓN Y RESPETO HACIA LOS ANIMALES

3.
Nombre:IMPLEMENTAR EL PROGRAMA SERVICIO SOCIAL DEJANDO HUELLA
Objetivos: 
INTEGRAR LA VISIÓN DE RESPETO Y PROTECCIÓN HACIA LOS ANIMALES EN EL SERVICIO SOCIAL OBLIGATORIO DE LOS ESTUDIANTES DE GRADO ONCE, A TRAVÉS DEL PROGRAMA “DEJANDO HUELLA”.
Actividades mga:
CAPACITAR A LOS GRUPOS DE INTERÉS RELACIONADOS CON LA PROTECCION Y EL BIENESTAR ANIMAL EN PROCESOS DE INCLUSIÓN 
Y RESPETO HACIA LOS ANIMALES

4.
Nombre:ALIANZAS ACADEMICAS Y EXPERIENCIAS 
Objetivos: 
FORTALECER LA ARTICULACIÓN CON INSTITUCIONES ACADÉMICAS Y CENTROS DE CONOCIMIENTO MEDIANTE LA REALIZACIÓN DE EVENTOS, ENCUENTROS Y ESPACIOS ACADÉMICOS, QUE PROMUEVAN EL INTERCAMBIO DE SABERES, LA GENERACIÓN DE EXPERIENCIAS FORMATIVAS Y LA PRODUCCIÓN DE CONOCIMIENTO APLICADO EN MATERIA DE PROTECCIÓN Y BIENESTAR ANIMAL.
Actividades mga:
CAPACITAR A LOS GRUPOS DE INTERÉS RELACIONADOS CON LA PROTECCION Y EL BIENESTAR ANIMAL EN PROCESOS DE INCLUSIÓN Y RESPETO HACIA LOS ANIMALES

5.
Nombre:CULTUTA Y GENERCION DE EXPERIENCIAS 
Objetivos: 
REALIZAR EXPERIENCIAS EXITOSAS EN LA INCLUSIÓN Y RESPETO POR LOS ANIMALES
Actividades mga:
REALIZAR EVENTOS DE PROMOCIÓN DE EXPERIENCIAS EXITOSAS EN LA INCLUSIÓN Y RESPETO POR LOS ANIMALES