"""remove unique constraint from action_plan number

Revision ID: 0abff2a75c12
Revises: 44220e0fed0e
Create Date: 2026-02-26 12:51:27.853089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0abff2a75c12'
down_revision = '44220e0fed0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_plan_activities', schema=None) as batch_op:
        batch_op.alter_column('deliverable',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('delivery_date',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('action_plans', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('action_plans_number_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_plans', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('action_plans_number_key'), ['number'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('action_plan_activities', schema=None) as batch_op:
        batch_op.alter_column('delivery_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('deliverable',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
