"""Add records table

Revision ID: 0bee1db45aed
Revises: 095637a2d6f7
Create Date: 2025-11-20 09:41:55.483665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bee1db45aed'
down_revision = '095637a2d6f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_type', sa.Enum('integer', 'decimal', 'boolean', 'text', 'date', 'category', name='indicator_data_type'), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('use_list', sa.Boolean(), nullable=True),
    sa.Column('allowed_values', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('indicator_id', sa.Integer(), nullable=True),
    sa.Column('municipio', sa.String(length=150), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo_poblacion', sa.String(length=100), nullable=False),
    sa.Column('detalle_poblacion', sa.JSON(), nullable=True),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('evidencia_url', sa.Text(), nullable=True),
    sa.Column('creado_por', sa.String(length=120), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    op.drop_table('indicators')
    # ### end Alembic commands ###
