"""add responsible_user_id to action_plans

Revision ID: 0dc7c01f341f
Revises: 7b55d8e8cb73
Create Date: 2026-04-06 16:27:12.183661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dc7c01f341f'
down_revision = '7b55d8e8cb73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsible_user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_action_plans_responsible_user_id'), ['responsible_user_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['responsible_user_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###

    # Migrar datos existentes: vincular responsible (texto) con users
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE action_plans
        SET responsible_user_id = u.id
        FROM users u
        WHERE action_plans.responsible IS NOT NULL
          AND action_plans.responsible_user_id IS NULL
          AND TRIM(action_plans.responsible) = CONCAT(u.first_name, ' ', u.last_name)
    """))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_plans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_action_plans_responsible_user_id'))
        batch_op.drop_column('responsible_user_id')

    # ### end Alembic commands ###
