"""add es_poblacional to indicator

Revision ID: 10d3fbdead5f
Revises: 191235d9f9e6
Create Date: 2026-01-26 14:53:50.139344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '10d3fbdead5f'
down_revision = '191235d9f9e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_poblacional', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('es_poblacional')

    # ### end Alembic commands ###
