"""Component now depends on Activity

Revision ID: 191235d9f9e6
Revises: c4f139077c9d
Create Date: 2026-01-21 11:57:02.107195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '191235d9f9e6'
down_revision = 'c4f139077c9d'
branch_labels = None
depends_on = None


from alembic import op
import sqlalchemy as sa


def upgrade():
    # 1️⃣ Agregar activity_id PERMITIENDO NULL
    op.add_column(
        "components",
        sa.Column("activity_id", sa.Integer(), nullable=True)
    )

    # 2️⃣ Crear una actividad "Migración automática" por estrategia
    op.execute("""
        INSERT INTO activities (strategy_id, description, active, created_at)
        SELECT id, 'Actividad generada por migración', true, NOW()
        FROM strategies
    """)

    # 3️⃣ Asignar componentes antiguos a la actividad creada
    op.execute("""
        UPDATE components c
        SET activity_id = a.id
        FROM activities a
        WHERE c.strategy_id = a.strategy_id
          AND a.description = 'Actividad generada por migración'
    """)

    # 4️⃣ Crear FK components → activities
    op.create_foreign_key(
        "fk_components_activity",
        "components",
        "activities",
        ["activity_id"],
        ["id"],
        ondelete="CASCADE"
    )

    # 5️⃣ Ahora sí: activity_id NOT NULL
    op.alter_column("components", "activity_id", nullable=False)

    # 6️⃣ Eliminar FK vieja
    op.drop_constraint(
        "components_strategy_id_fkey",
        "components",
        type_="foreignkey"
    )

    # 7️⃣ Eliminar strategy_id
    op.drop_column("components", "strategy_id")



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strategy_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('components_strategy_id_fkey'), 'strategies', ['strategy_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('activity_id')

    # ### end Alembic commands ###
