"""add lugar to action_plans

Revision ID: 1d53b5488c82
Revises: 0a54a0401589
Create Date: 2026-04-06 11:34:27.118607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d53b5488c82'
down_revision = '0a54a0401589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lugar', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_plans', schema=None) as batch_op:
        batch_op.drop_column('lugar')

    # ### end Alembic commands ###
