"""rename description to objective_name in component_objectives

Revision ID: 216d9b7f50f0
Revises: 39788f38c67d
Create Date: 2026-02-02 19:12:54.498526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216d9b7f50f0'
down_revision = '39788f38c67d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component_objectives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('objective_name', sa.String(length=255), nullable=False))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component_objectives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('objective_name')

    # ### end Alembic commands ###
