"""add cascade deletes

Revision ID: 31b98c7efec0
Revises: 3c91d2a3dc04
Create Date: 2026-02-04 23:32:04.638882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31b98c7efec0'
down_revision = '3c91d2a3dc04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_column('active')

    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fields_table_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tables', ['table_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('records_table_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tables', ['table_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('tables_dataset_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'datasets', ['dataset_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tables_dataset_id_fkey'), 'datasets', ['dataset_id'], ['id'])

    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('records_table_id_fkey'), 'tables', ['table_id'], ['id'])

    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fields_table_id_fkey'), 'tables', ['table_id'], ['id'])

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
