"""move deliverable and date to activity level

Revision ID: 44220e0fed0e
Revises: da4b5089bbfa
Create Date: 2026-02-25 15:24:32.823306

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '44220e0fed0e'
down_revision = 'da4b5089bbfa'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('action_plan_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deliverable', sa.Text(), nullable=True))        # ← True
        batch_op.add_column(sa.Column('delivery_date', sa.Date(), nullable=True))      # ← True
        batch_op.add_column(sa.Column('evidence_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('reported_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))

    with op.batch_alter_table('action_plans', schema=None) as batch_op:
        batch_op.drop_column('score')
        batch_op.drop_column('delivery_date')
        batch_op.drop_column('deliverable')
        batch_op.drop_column('reported_at')
        batch_op.drop_column('evidence_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evidence_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reported_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deliverable', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('delivery_date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('action_plan_activities', schema=None) as batch_op:
        batch_op.drop_column('score')
        batch_op.drop_column('reported_at')
        batch_op.drop_column('evidence_url')
        batch_op.drop_column('delivery_date')
        batch_op.drop_column('deliverable')

    # ### end Alembic commands ###
