"""restore active column

Revision ID: 46643428ef89
Revises: 31b98c7efec0
Create Date: 2026-02-04 23:34:15.273324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46643428ef89'
down_revision = '31b98c7efec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.drop_column('active')

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
