"""refactor action plans: move fields to activity, add responsible and description

Revision ID: 4e73ea44aa75
Revises: 0abff2a75c12
Create Date: 2026-02-26 15:23:41.333354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e73ea44aa75'
down_revision = '0abff2a75c12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_plan_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('objective_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('requires_boss_assistance', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('responsible', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'component_objectives', ['objective_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('action_plans', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('action_plans_objective_id_fkey'), type_='foreignkey')
        batch_op.drop_column('number')
        batch_op.drop_column('requires_boss_assistance')
        batch_op.drop_column('objective_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('objective_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('requires_boss_assistance', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('action_plans_objective_id_fkey'), 'component_objectives', ['objective_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('action_plan_activities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('description')
        batch_op.drop_column('responsible')
        batch_op.drop_column('requires_boss_assistance')
        batch_op.drop_column('objective_id')

    # ### end Alembic commands ###
