"""remove activites_performed from reports

Revision ID: 533146603c20
Revises: fe155f3747e5
Create Date: 2026-03-05 16:57:44.183457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '533146603c20'
down_revision = 'fe155f3747e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('activities_performed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activities_performed', sa.TEXT(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
