"""add order to component_indicators

Revision ID: 56537bc86e19
Revises: bf579dc24eaf
Create Date: 2026-02-19 14:43:57.821682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56537bc86e19'
down_revision = 'bf579dc24eaf'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('component_indicators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=False, server_default='0'))

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component_indicators', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
