"""restructure action plans with plan_objectives

Revision ID: 6ec15de068df
Revises: 4e73ea44aa75
Create Date: 2026-02-26 15:44:58.083617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ec15de068df'
down_revision = '4e73ea44aa75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_plan_objectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_plan_id', sa.Integer(), nullable=False),
    sa.Column('objective_id', sa.Integer(), nullable=True),
    sa.Column('objective_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['action_plan_id'], ['action_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['objective_id'], ['component_objectives.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_plan_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_objective_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('action_plan_activities_objective_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('action_plan_activities_action_plan_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'action_plan_objectives', ['plan_objective_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('objective_id')
        batch_op.drop_column('responsible')
        batch_op.drop_column('action_plan_id')

    with op.batch_alter_table('action_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsible', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_plans', schema=None) as batch_op:
        batch_op.drop_column('responsible')

    with op.batch_alter_table('action_plan_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action_plan_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('responsible', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('objective_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('action_plan_activities_action_plan_id_fkey'), 'action_plans', ['action_plan_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('action_plan_activities_objective_id_fkey'), 'component_objectives', ['objective_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('plan_objective_id')

    op.drop_table('action_plan_objectives')
    # ### end Alembic commands ###
