"""add reported_by_user_id to action_plan_activities

Revision ID: 72e49ed13e05
Revises: cfe0febe0a94
Create Date: 2026-03-26 10:22:03.338311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72e49ed13e05'
down_revision = 'cfe0febe0a94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_plan_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reported_by_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['reported_by_user_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_plan_activities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reported_by_user_id')

    # ### end Alembic commands ###
