"""Fix strategy_id foreign key

Revision ID: 9026c1b02443
Revises: bde5d6c78e4c
Create Date: 2025-11-26 17:31:58.629917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9026c1b02443'
down_revision = 'bde5d6c78e4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.alter_column('strategy_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('component_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('records_indicator_id_fkey'), type_='foreignkey')
        batch_op.drop_column('indicator_id')
        batch_op.drop_column('creado_por')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creado_por', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('indicator_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('records_indicator_id_fkey'), 'indicators', ['indicator_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('component_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('strategy_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
