"""add group_name and group_required to component_indicators

Revision ID: 90be1b8eb66c
Revises: 533146603c20
Create Date: 2026-03-11 16:59:36.363946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90be1b8eb66c'
down_revision = '533146603c20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component_indicators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('group_required', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component_indicators', schema=None) as batch_op:
        batch_op.drop_column('group_required')
        batch_op.drop_column('group_name')

    # ### end Alembic commands ###
