"""add conditional_schema to indicators

Revision ID: adf470c221dc
Revises: 216d9b7f50f0
Create Date: 2026-02-02 21:59:04.415229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'adf470c221dc'
down_revision = '216d9b7f50f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conditional_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.drop_column('has_conditional')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_conditional', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('conditional_schema')

    # ### end Alembic commands ###
