"""Clean indicator model

Revision ID: bde5d6c78e4c
Revises: eff2cdf8f67e
Create Date: 2025-11-26 17:07:07.253348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bde5d6c78e4c'
down_revision = 'eff2cdf8f67e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.drop_column('use_list')
        batch_op.drop_column('allowed_values')
        batch_op.drop_column('required')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('allowed_values', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('use_list', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
