"""add lugar to action_plans

Revision ID: c323ceacc154
Revises: 1d53b5488c82
Create Date: 2026-04-06 11:45:18.395944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c323ceacc154'
down_revision = '1d53b5488c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_plan_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lugar', sa.String(length=255), nullable=True))

    with op.batch_alter_table('action_plans', schema=None) as batch_op:
        batch_op.drop_column('lugar')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lugar', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    with op.batch_alter_table('action_plan_activities', schema=None) as batch_op:
        batch_op.drop_column('lugar')

    # ### end Alembic commands ###
