"""add manual_value to strategy_metrics

Revision ID: d4862f905027
Revises: e081785e1830
Create Date: 2026-03-25 14:27:30.257486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4862f905027'
down_revision = 'e081785e1830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manual_value', sa.Numeric(precision=14, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_metrics', schema=None) as batch_op:
        batch_op.drop_column('manual_value')

    # ### end Alembic commands ###
