"""add component_public_policies table

Revision ID: dd8145f0499d
Revises: 25ef76ea090b
Create Date: 2026-03-18 02:26:59.703057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd8145f0499d'
down_revision = '25ef76ea090b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component_public_policies',
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('public_policy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['public_policy_id'], ['public_policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('component_id', 'public_policy_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('component_public_policies')
    # ### end Alembic commands ###
