"""add recurrence fields to action_plan_activities

Revision ID: f7eb2d4a01cb
Revises: 72e49ed13e05
Create Date: 2026-03-26 11:14:27.627617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7eb2d4a01cb'
down_revision = '72e49ed13e05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_plan_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurrence_group_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('recurrence_rule', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_action_plan_activities_recurrence_group_id'), ['recurrence_group_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_plan_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_plan_activities_recurrence_group_id'))
        batch_op.drop_column('recurrence_rule')
        batch_op.drop_column('recurrence_group_id')

    # ### end Alembic commands ###
